---
####################################################
# Setup and internal network and a router          #
####################################################
- name: Setup an internal network and and a router 
  hosts: controller
  gather_facts: no
  sudo: yes
  vars:
     - login_username: admin
     - login_password: password
     - login_tenant_name: admin
     - tenant_name: admin
     - external_network: public
     - internal_network: net1
     - internal_subnet: net1subnet
     - router: router1
  tasks:
     - name: Create an internal network 
       quantum_network: 
           name="{{ internal_network }}"
           state=present
           tenant_name="{{ tenant_name }}"
           login_username="{{ login_username }}"
           login_password="{{ login_password }}"
           login_tenant_name="{{ login_tenant_name }}"

     - name: Creating a subnet for the internal network
       quantum_subnet: 
           state=present
           tenant_name="{{ tenant_name }}"
           login_username="{{ login_username }}"
           login_password="{{ login_password }}"
           login_tenant_name="{{ login_tenant_name }}"
           network_name="{{ internal_network }}"
           name="{{ internal_subnet }}"
           cidr=192.168.100.0/24
 
     - name: Creating a router
       quantum_router: state=present
           tenant_name="{{ tenant_name }}"
           login_username="{{ login_username }}"
           login_password="{{ login_password }}"
           login_tenant_name="{{ login_tenant_name }}"
           name="{{ router }}"

     - name: Attaching an interface to the router
       quantum_router_interface:
           tenant_name="{{ tenant_name }}"
           login_username="{{ login_username }}"
           login_password="{{ login_password }}"
           login_tenant_name="{{ login_tenant_name }}"
           router_name="{{ router }}"
           subnet_name="{{ internal_subnet }}"

     - name: Setting a router's gateway
       quantum_router_gateway:
           state=present 
           login_username="{{ login_username }}"
           login_password="{{ login_password }}"
           login_tenant_name="{{ login_tenant_name }}"
           router_name="{{ router }}"
           network_name="{{ external_network }}"
           
