---
#####################################################
# Setup internal and external networks and a router #
#####################################################
- name: Setup an internal network and and a router 
  hosts: controller
  gather_facts: no
  sudo: yes
  vars:
     - login_username: admin
     - login_password: password
     - login_tenant_name: admin
     - tenant_name: admin
     - external_network: public
     - internal_network: net1
     - internal_subnet: net1subnet
     - router: router1
  tasks:
     - name: Create external network - neutron
       quantum_network:
           state: present
           login_username: "{{ login_username }}"
           login_password: "{{ login_password }}"
           login_tenant_name: "{{ login_tenant_name }}"
           name: public
           provider_network_type: vlan
           provider_physical_network: myphysnet
           provider_segmentation_id: 190
           router_external: yes

     - name: Create subnet for external network - neutron
       quantum_subnet:
           state: present
           login_username: "{{ login_username }}"
           login_password: "{{ login_password }}"
           login_tenant_name: "{{ login_tenant_name }}"
           tenant_name: "{{ tenant_name }}"
           network_name: public
           name: external-subnet
           enable_dhcp: False
           gateway_ip: "{{ external_gw }}"
           cidr: "{{ external_cide }}"
           allocation_pool_start: "{{ external_allocation_pool_start }}"
           allocation_pool_end: "{{ allocation_pool_end }}"

     - name: Create an internal network 
       quantum_network: 
           name="{{ internal_network }}"
           state=present
           tenant_name="{{ tenant_name }}"
           login_username="{{ login_username }}"
           login_password="{{ login_password }}"
           login_tenant_name="{{ login_tenant_name }}"

     - name: Creating a subnet for the internal network
       quantum_subnet: 
           state=present
           tenant_name="{{ tenant_name }}"
           login_username="{{ login_username }}"
           login_password="{{ login_password }}"
           login_tenant_name="{{ login_tenant_name }}"
           network_name="{{ internal_network }}"
           name="{{ internal_subnet }}"
           cidr=192.168.100.0/24
 
     - name: Creating a router
       quantum_router: state=present
           tenant_name="{{ tenant_name }}"
           login_username="{{ login_username }}"
           login_password="{{ login_password }}"
           login_tenant_name="{{ login_tenant_name }}"
           name="{{ router }}"

     - name: Attaching an interface to the router
       quantum_router_interface:
           tenant_name="{{ tenant_name }}"
           login_username="{{ login_username }}"
           login_password="{{ login_password }}"
           login_tenant_name="{{ login_tenant_name }}"
           router_name="{{ router }}"
           subnet_name="{{ internal_subnet }}"

     - name: Setting a router's gateway
       quantum_router_gateway:
           state=present 
           login_username="{{ login_username }}"
           login_password="{{ login_password }}"
           login_tenant_name="{{ login_tenant_name }}"
           router_name="{{ router }}"
           network_name="{{ external_network }}"
